# Generated by Django 5.2 on 2025-04-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='contraseña',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='pin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
